counter/links_counter/config/routes.rb
Rails.application.routes.draw do
  root 'counter#menu'
  #get 'counter/menu'
  get '/menu', to: 'counter#menu'
  #get 'counter/incr'
  get '/incr', to: 'counter#incr'
  #get 'counter/decr'
  get '/decr', to: 'counter#decr'
  #get 'counter/reset'
  get '/reset', to: 'counter#reset'
  #get 'counter/health'
  get '/health', to: 'counter#health'
  #get 'counter/metrics'
  get '/metrics', to: 'counter#metrics'
  #get 'counter/get'
  get '/get', to: 'counter#get'
  #get 'counter/crash'
  get '/crash', to: 'counter#crash'
  #get 'counter/yolo'
  get '/yolo', to: 'counter#yolo'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

counter/links_counter/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

counter/links_counter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

counter/links_counter/app/controllers/counter_controller.rb
class CounterController < ApplicationController
  def menu 
  end

  def get
    begin
      @counter = REDIS
      @value_counter = @counter.get("1")
      @result = @value_counter.to_i
    rescue Errno::ECONNREFUSED, ::Redis::CannotConnectError
      @result = "Something went wrong! Check health of your counter using this link: "
    end
  end

  def incr
    begin
      @counter = REDIS
      @value_counter = @counter.incr("1")
      @result = @value_counter.to_i
      $incr_stat.incr
    rescue Errno::ECONNREFUSED, ::Redis::CannotConnectError
      @result= "Something went wrong! Check health of your counter using this link: "
    end
  end

  def decr
    begin
      @counter = REDIS
      @value_counter = @counter.get("1")
      case
      when @value_counter.to_i == 0
        @result = @value_counter.to_i
      when @value_counter.to_i > 0
        @result = @counter.decr("1").to_i
        $decr_stat.incr
      end
    rescue Errno::ECONNREFUSED, ::Redis::CannotConnectError
      @result = "Something went wrong! Check health of your counter using this link: "
    end
  end

  def reset
    begin
      @counter = REDIS
      @counter.set("1", "0")
      @result = @counter.get("1").to_i
      $reset_stat.incr
    rescue Errno::ECONNREFUSED, ::Redis::CannotConnectError
      @result = "Something went wrong! Check health of your counter using this link: "
    end
  end

  def health
    begin
      if REDIS.ping == "PONG"
        @health = "Redis database connection is OK!"
      end
    rescue Errno::ECONNREFUSED, ::Redis::CannotConnectError
      @health = "Redis database connection Failed!"
    end
  end

  def metrics
      @incr_number = $incr_stat.print
      @decr_number = $decr_stat.print
      @reset_number = $reset_stat.print
  end

  # Intentional application crash with confirmation !
  def crash
    exit!
  end

  def yolo
    exit!
  end
end

counter/links_counter/app/helpers/application_helper.rb
module ApplicationHelper
end

counter/links_counter/app/helpers/counter_helper.rb
module CounterHelper
end

counter/links_counter/app/views/counter/decr.html.erb
<style>
  h1, h3 {
    text-align: center;
  }
</style>

<h1>
  <% if @result.is_a?(Integer)%>
   Counter value: <%= @result %>
  <% else %>
    <%= @result %><%=link_to("Counter health", health_path) %> 
  <%end %>
  </h1><br />
<h3><%= link_to("Back to Main page", menu_path, class: "btn btn-lg btn-primary")%></h3>

counter/links_counter/app/views/counter/get.html.erb
<style>
  h1, h3 {
    text-align: center;
  }
</style>


<h1> 
  <% if @result.is_a?(Integer)%>
   Counter value: <%= @result %>
  <% else %>
    <%= @result %><%=link_to("Counter health", health_path) %> 
  <%end %>
</h1><br />
<h3><%= link_to("Back to Main page", menu_path, class: "btn btn-lg btn-primary")%></h3>

counter/links_counter/app/views/counter/health.html.erb
<style>
  h1, h3 {
    text-align: center;
  }
</style>


<h1>Health status: <%= @health %></h1><br />
<h3><%= link_to("Back to Main page", menu_path, class: "btn btn-lg btn-primary")%></h3>

counter/links_counter/app/views/counter/incr.html.erb
<style>
  h1, h3 {
    text-align: center;
  }
</style>


<h1> 
  <% if @result.is_a?(Integer)%>
   Counter value: <%= @result %>
  <% else %>
    <%= @result %><%=link_to("Counter health", health_path) %> 
  <%end %>
</h1><br />
<h3><%= link_to("Back to Main page", menu_path, class: "btn btn-lg btn-primary")%></h3>

counter/links_counter/app/views/counter/menu.html.erb
<div class="center jumbotron">
<style>
  h1, h3 {
    text-align: center;
    font-family: monaco;
  }
</style>

<h1>Welcome to Rails Pagecounter</h1>
<h3><%=link_to image_tag("counter.png", alt: "Counter") %></h3>
</div>

counter/links_counter/app/views/counter/metrics.html.erb
<style>
  h1, h3, h4 {
    text-align: center;
  }
</style>


<h1>Increment counter has been used: <%= @incr_number %></h1><br />
<h1>Decrement counter has been used: <%= @decr_number %></h1><br />
<h1>Reset counter has been used: <%= @reset_number %></h1><br />
<h1><br />
<h3><%= link_to("Back to Main page", menu_path, class: "btn btn-lg btn-primary")%></h3>

counter/links_counter/app/views/counter/reset.html.erb
<style>
  h1, h3 {
    text-align: center;
  }
</style>

<h1> 
  <% if @result.is_a?(Integer)%>
   Counter value: <%= @result %>
  <% else %>
    <%= @result %><%=link_to("Counter health", health_path) %> 
  <%end %>
</h1><br />
<h3><%= link_to("Back to Main page", menu_path, class: "btn btn-lg btn-primary")%></h3>

counter/links_counter/app/views/layouts/_footer.html.erb
<footer class="footer">
    <strong>Boys don't cry!</strong>
</footer>

counter/links_counter/app/views/layouts/_header.html.erb
<header class="navbar navbarfixed-top navbar-inverse">
    <div class="container">
        <%= link_to "Rails Pagecounter", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
                <li><%= link_to("Get", get_path) %></li>
                <li><%= link_to("Increment", incr_path) %></li>
                <li><%= link_to("Decrement", decr_path) %></li>
                <li><%= link_to("Reset", reset_path) %></li>
                <li><%= link_to("Health", health_path) %></li>
                <li><%= link_to("Metrics", metrics_path)%></li>
                <li><%= link_to("Crash", crash_path ,data: { confirm: "Are you sure you WANT to CRASH the counter?" })%></li>
                <li><%= link_to("#YOLO", yolo_path)%></li>
            </ul>
        </nav>
    </div>   
</header>

counter/links_counter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LinksCounter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
     <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>